name: Deploy Development

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'development'

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: auth-service
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Download Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition auth-service-dev-task \
            --query taskDefinition > task-definition.json

      - uses: aws-actions/amazon-ecs-render-task-definition@v1
        id: task-def
        with:
          task-definition: task-definition.json
          container-name: auth-service
          image: ${{ steps.login-ecr.outputs.registry }}/auth-service:latest

      - uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: auth-service-dev-task-service
          cluster: dev-cluster
          wait-for-service-stability: true