on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker Image
        run: docker build -t auth-service .

      - name: Run Jest Tests inside Docker
        run: docker run --rm -v $PWD/coverage:/app/coverage auth-service npm run coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: 7d8f3d55a22eeca9127982cdc065b2da37089fe9
          SONAR_PROJECT_KEY: job-portal-application_auth_service
          SONAR_ORGANIZATION: job-portal-application
